//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pokemon_Drawing_ver2.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pokemon_Drawing_ver2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   abomasnow-mega.png,no460 눈설왕-(메가진화).png
        ///abomasnow.png,no460 눈설왕.png
        ///abra.png,no063 캐이시.png
        ///absol-mega.png,no359 앱솔-(메가진화).png
        ///absol.png,no359 앱솔.png
        ///accelgor.png,no617 어지리더.png
        ///aegislash-blade.png,no681 킬가르도-(블레이드폼).png
        ///aegislash.png,no681 킬가르도.png
        ///aerodactyl-mega.png,no142 프테라-(메가진화).png
        ///aerodactyl.png,no142 프테라.png
        ///aggron-mega.png,no306 보스로라-(메가진화).png
        ///aggron.png,no306 보스로라.png
        ///aipom.png,no190 에이팜.png
        ///alakazam-mega.png,no065 후딘-(메가진화).png
        ///alakazam.png,no065 후딘.png
        ///alcremie-caramel-swirl-ber[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string image_name {
            get {
                return ResourceManager.GetString("image_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap image_regular_easy {
            get {
                object obj = ResourceManager.GetObject("image_regular_easy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap image_regular_hard {
            get {
                object obj = ResourceManager.GetObject("image_regular_hard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap image_regular_normal {
            get {
                object obj = ResourceManager.GetObject("image_regular_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap image_shiny_easy {
            get {
                object obj = ResourceManager.GetObject("image_shiny_easy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap image_shiny_hard {
            get {
                object obj = ResourceManager.GetObject("image_shiny_hard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap image_shiny_normal {
            get {
                object obj = ResourceManager.GetObject("image_shiny_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Bitmap pokeball {
            get {
                object obj = ResourceManager.GetObject("pokeball", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   (아이콘)과(와) 유사한 System.Drawing.Icon 형식의 지역화된 리소스를 찾습니다.
        /// </summary>
        internal static System.Drawing.Icon pokeball_icon {
            get {
                object obj = ResourceManager.GetObject("pokeball_icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   1,�̻��ؾ�,Bulbasaur
        ///2,�̻���Ǯ,Ivysaur
        ///3,�̻��ز�,Venusaur
        ///4,���̸�,Charmander
        ///5,���ڵ�,Charmeleon
        ///6,���ڸ�,Charizard
        ///7,���α�,Squirtle
        ///8,��Ϻα�,Wartortle
        ///9,�źϿ�,Blastoise
        ///10,ĳ����,Caterpie
        ///11,�ܵ���,Metapod
        ///12,������,Butterfree
        ///13,������,Weedle
        ///14,������,Kakuna
        ///15,��ħ��,Beedrill
        ///16,����,Pidgey
        ///17,����,Pidgeotto
        ///18,������,Pidgeot
        ///19,����,Rattata
        ///20,��Ʈ��,Raticate
        ///21,������,Spearow
        ///22,����帱��,Fearow
        ///23,�ƺ�,Ekans
        ///24,�ƺ�ũ,Arbok
        ///25,��ī��,Pikachu
        ///26,������,Raichu
        ///27,�𷡵���,Sandshrew
        ///28,����,Sands[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pokemon_no_kor_eng {
            get {
                return ResourceManager.GetString("pokemon_no_kor_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   bulbasaur,이상해씨
        ///ivysaur,이상해풀
        ///venusaur,이상해꽃
        ///charmander,파이리
        ///charmeleon,리자드
        ///charizard,리자몽
        ///squirtle,꼬부기
        ///wartortle,어니부기
        ///blastoise,거북왕
        ///caterpie,캐터피
        ///metapod,단데기
        ///butterfree,버터플
        ///weedle,뿔충이
        ///kakuna,딱충이
        ///beedrill,독침붕
        ///pidgey,구구
        ///pidgeotto,피죤
        ///pidgeot,피죤투
        ///rattata,꼬렛
        ///raticate,레트라
        ///spearow,깨비참
        ///fearow,깨비드릴조
        ///ekans,아보
        ///arbok,아보크
        ///pikachu,피카츄
        ///raichu,라이츄
        ///sandshrew,모래두지
        ///sandslash,고지
        ///nidoran♀,니드런♀
        ///nidorina,니드리나
        ///nidoqueen,니드퀸
        ///nidoran♂,니드런♂
        ///nidorino,니드리노
        ///nidoking,니드킹
        ///clefairy,삐삐
        ///clefable,픽시
        ///vulpix,식스테일        ///[나머지 문자열은 잘림]&quot;;과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string pokemon_translate {
            get {
                return ResourceManager.GetString("pokemon_translate", resourceCulture);
            }
        }
    }
}
